workflows:
  simple-workflow:
    name: Native Android
    max_build_duration: 60
    scripts:
      - name: Android emulator 
        script: emulator -avd emulator > /dev/null 2>&1 &
      - name: Run tests
        script: ./gradlew test
      - name: Instrumented unit tests 
        script: ./gradlew connectedAndroidTest
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - j.bilongo@ynote.africa
